apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cdocker-build-push-cached
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/git-source/Dockerfile
      - name: pathToContext
        description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/git-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: inventory-files
      image: docker.io/ubuntu
      command: ['/bin/bash'] 
      args: ['-c', 'du -a'] 
    - name: build-push-step
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
        - --cache=true 
        - --cache-repo=9.24.159.185:5000