apiVersion: tekton.dev/v1alpha1
kind: Task
metadata: 
  name: deploy-using-kubectl-task
spec:
  inputs: 
    resources: 
    - name: git-source
      type: git
    - name: image-out
      type: image
  steps:
  - name: show-image-name
    image: docker.io/ubuntu
    command: ['/bin/bash'] 
    args: ['-c', 'echo deploy-using-kubectl-task  $IMG'] 
    env:
      - name: IMG
        value: ${inputs.resources.image-out.url}
  - name: modify-yaml
    image: ubuntu
    command: ['/bin/bash']
    args: ['-c', 'find ./git-source/config -type f -exec sed -i -e s!"image: PIPELINE_REPLACE:latest"!"image: ${IMG}"!g {} \;']
    env:
      - name: IMG
        value: ${inputs.resources.image-out.url}
  - name: show-config
    image: docker.io/ubuntu
    command: ['/bin/bash'] 
    args: ['-c', 'cat ./git-source/config/*'] 
    env:
      - name: IMG
        value: ${inputs.resources.image-out.url}
  - name: install-new
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args: 
    - 'apply'
    - '-f'
    - './git-source/config'

  - name: pipeline-run-summary
    image: jduimovich/summary 
    workingDir: "/workspace/git-source/"
    command: ['bash'] 
    args: ['/script.sh']
    env:
      - name: REPO
        value: ${inputs.resources.git-source.url}
      - name: IMAGE
        value: ${inputs.resources.image-out.url}
      - name: DEPLOY
        value: "/workspace/git-source/config"

