apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: <mygithubrepository.git>
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
  - name: url
    value: docker.io/<mydockerusername>/<myappname>
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: microclimate-pipeline-run
spec:
  pipelineRef:
    name: microclimate-pipeline # Change if you want to use a different pipeline
  params:
    - name: chart-dir
      value: "chart"
    - name: repository-name
      value: "myreponame"
    - name: release-name
      value: "myrelease"
    - name: target-namespace
      value: "default"
    - name: image-name
      value: "<mydockerusername>/<myappname>"
    - name: image-tag
      value: "latest"
    # Replace what's in values.yaml for image repository and tag according to below pattern
    - name: replace-repo
      value: "<replaceme>"
    - name: replace-tag
      value: "<replaceme>"
  trigger:
    type: manual
  serviceAccount: "default"
  resources:
  - name: git-source
    resourceRef:
      name: git-source
  - name: docker-image
    resourceRef:
      name: docker-image
